[build]
  base = "jaystarbliss-studios.name.ng"
  publish = "htdocs"

[[redirects]]
  from = "/pages/features/Games-section"
  to = "/pages/features/games.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/features/Games-section/*"
  to = "/pages/features/games.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/features/Games-section.html"
  to = "/pages/features/games.html"
  status = 301
  force = true

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 301
  force = true

[[redirects]]
  from = "/programming"
  to = "/programming.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/school/school-admin-portal"
  to = "/pages/school/school-admin-portal.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/resources/school-resources"
  to = "/pages/resources/school-resources.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/features/news"
  to = "/pages/features/news.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/features/games"
  to = "/pages/features/games.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/features/MAGIC-PARTICLES"
  to = "/pages/features/MAGIC-PARTICLES.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/tutor-portal"
  to = "/pages/dashboard/tutor-portal.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/student-portal"
  to = "/pages/dashboard/student-portal.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/staff-portal"
  to = "/pages/dashboard/staff-portal.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/school-portal"
  to = "/pages/dashboard/school-portal.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/paystack-checkout"
  to = "/pages/dashboard/paystack-checkout.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/parent-portal"
  to = "/pages/dashboard/parent-portal.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/dummy-checkout"
  to = "/pages/dashboard/dummy-checkout.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/dashboard/admin-dashboard"
  to = "/pages/dashboard/admin-dashboard.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/auth/login"
  to = "/pages/auth/login.html"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
